# para expor o trace - somente para testes
# server.error.include-stacktrace = always
spring.web.error.include-message=always

# para nao expor o trace
spring.web.error.include-stacktrace = never
# server.error.include-message=never

# Conexao com o banco H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=554805
spring.datasource.password=151005

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create

# http://localhost:8080/h2-console/